version: "3.8"

services:
  # Mysql database container
  db:
    image: mysql
    container_name: ztpai_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: Europe/Warsaw
    networks:
      - ztpai-project

  # Phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: ztpai_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      TZ: Europe/Warsaw
    networks:
      - ztpai-project

  # Symfony apache api container
  backend:
    build:
      context: ./backend
      dockerfile: ../.docker/php/Dockerfile
    container_name: ztpai_symfony
    ports:
      - "8082:80"
    environment:
      TZ: Europe/Warsaw
      SHELL_VERBOSITY: 2
    volumes:
      - ./.docker/php/vhosts:/etc/apache2/sites-enabled
      - ./backend:/var/www/backend:delegated
      - /var/www/backend/vendor
      - /var/www/backend/var
    tty: true
    stdin_open: true
    restart: always
    networks:
      - ztpai-project

  # React frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ztpai_react
    restart: on-failure
    depends_on:
      - backend
    networks:
      - ztpai-project
    volumes:
      # this will mount the ui folder which contains the code to the docker container
      - ./frontend:/var/www/frontend
      # this will mount the node_modules folder for faster performance
      - /var/www/frontend/node_modules
    ports:
      - "8081:8081"
    environment:
      NODE_OPTIONS: --trace-warnings

networks:
  ztpai-project:

volumes:
  db-data: