version: "3.8"
services:
  # Mysql database container
  db:
    image: mysql
    container_name: ztpai_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - tutorial

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: ztpai_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - tutorial

  # Symfony apache api container
  api:
    build: docker/php
    container_name: ztpai_symfony
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - tutorial

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure
    # below line starts the project
    # command: "npm start"
    depends_on:
      - api
    networks:
      - tutorial
    volumes:
      # this will mount the ui folder which contains the code to the docker container
      - ./frontend:/var/www/frontend:delegated
      # this will mount the node_modules folder for faster performance
      - nodemodules:/var/www/frontend/node_modules
    ports:
      - "5173:5173"

networks:
  tutorial:

volumes:
  db-data:
  nodemodules: { }