version: "3.8"

services:
  # Mysql database container
  db:
    image: mysql
    container_name: ztpai_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - ztpai-project

  # Phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: ztpai_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - ztpai-project

  # Symfony apache api container
  api:
    build:
      context: ./api
      dockerfile: ../docker/php/Dockerfile
    container_name: ztpai_symfony
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./api:/var/www/api:delegated
      - /var/www/api/vendor
    restart: always
    networks:
      - ztpai-project

  # React frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ztpai_react
    restart: on-failure
    depends_on:
      - api
    networks:
      - ztpai-project
    volumes:
      # this will mount the ui folder which contains the code to the docker container
      - ./frontend:/var/www/frontend
      # this will mount the node_modules folder for faster performance
      - /var/www/frontend/node_modules
    ports:
      - "8081:8081"

networks:
  ztpai-project:

volumes:
  db-data: